preset: psr2

enabled:
  - duplicate_semicolon
  - empty_return
  - join_function
  - object_operator
  - remove_lines_between_uses
  - short_array_syntax
  - standardize_not_equal
  - unused_use
  - whitespacy_lines

finder:
  name:
    - "*.php"