language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

env:
  global:
    - COMPOSER_DISCARD_CHANGES=1

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

branches:
  only:
    master

before_script:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - composer check-style
  - composer phpstan

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
